[[pages]]
path = "./pages/1_introducao.py"
name = "Datathon - Fase 5"
icon = "ğŸ–¥ï¸"

[[pages]]
path = "./pages/2_passos_magicos"

[[pages]]
path = "./pages/3_eda.py"
name = "ExploraÃ§Ã£o e Insights"
icon = "ğŸ“ˆ"

[[pages]]
path = "./pages/4_modelos.py"
name = "Modelos"
icon = "âš™ï¸"

[[pages]]
path = "./pages/5_conclusao.py"
name = "ConclusÃ£o"
icon = "ğŸ¯"

